#! /bin/sh
cc `pkg-config --static --cflags kcgi-html sqlbox` -c -o cgi.o main.c
cc -static -o cgi cgi.o `pkg-config --static --libs kcgi-html sqlbox`
[ -d /var/www/cgi-bin/db ] || doas mkdir /var/www/cgi-bin/db
doas chown www:www /var/www/cgi-bin/db
doas chmod 0700 /var/www/cgi-bin/db
doas install -o www -g www -m 0500 cgi /var/www/cgi-bin
doas install -o www -g www -m 0500 db.db /var/www/cgi-bin/db.db
doas rcctl enable slowcgi
doas rcctl start slowcgi
doas rcctl check slowcgi
doas rcctl restart httpd
