#! /bin/sh
cc `pkg-config --static --cflags kcgi-html ksql` -c -o cgi.o main.c
cc -static -o cgi cgi.o `pkg-config --static --libs kcgi-html ksql`
doas install -o www -g www -m 0500 cgi /var/www/cgi-bin
doas install -o www -g www -m 0500 db.db /var/www/cgi-bin
doas rcctl enable slowcgi
doas rcctl start slowcgi
doas rcctl check slowcgi
doas rcctl restart httpd
